
version: "3.7"
services:
    django:
        image: django4:v0
        restart: unless-stopped
        build:
            context: .
        ports:
            - "8000:8000"

    react:
        image: ds_frontend:v0
        restart: unless-stopped
        build:
            context: ./app/
        ports:
            - "3000:3000"
