# Generated by Django 3.1.14 on 2022-01-31 15:02

from django.db import migrations


def function_that_raises_error(apps, schema_editor):
    bla = 1 / 0


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_pokemon_data"),
    ]

    operations = [
        migrations.RunPython(
            function_that_raises_error, reverse_code=migrations.RunPython.noop
        ),
    ]
